config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users#, :skip => [:registrations]

  devise_scope :user do
    resources :users
    get 'login', to: 'devise/sessions#new'
    get 'edit', to: 'devise/registrations#edit', as: :edit_myaccount
    delete 'logout', to: 'devise/sessions#destroy'
    get 'users/new', to: 'users#new', as: :sign_up
    post 'users/new', to: 'users#create'
    get 'users', to: 'users#index', as: :index
    patch "users/:id", to: "users#update"
    post 'users/:id/edit', to: 'users#update'
    get 'notifications', to: 'notifications#show', as: :notifications_show
  end



  authenticated :user do
    resources :areas
    post 'areas/:id.pdf', to: 'areas#report', as: :report
    get 'areas/:id.pdf', to: 'areas#report'
    resources :recommendations, except: :index do
      resources :goals
    end
    resources :goals
    resources :alerts
    patch '/hide/:id', to: 'alerts#hide', as: 'hide'
    patch '/unhide/:id', to: 'alerts#unhide', as: 'unhide'


    resources :evidences, except: :index
    resources :evidencefiles, only: [:create, :destroy]
    # Routes for authenticated users
    root to: 'areas#index', as: :authenticated_root
    #get "/areas", to: 'areas#index'
  end

  unauthenticated :user do
    get "/areas", to: redirect('login')
  end
  root to: redirect('login')

  resources :notifications do
    collection do
      get 'mark_as_read'
      get 'remove_all'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
    validates :name, :time_beg, :time_limit, :number, presence: true
    validate :time_limit_cannot_be_before_time_beg
    belongs_to :area
    has_many :evidences, :dependent => :destroy
    has_many :goals, :dependent => :destroy

    def time_limit_cannot_be_before_time_beg
        if time_limit < time_beg
            errors.add(:time_limit, "La fecha límite no puede ser menor a la inicial.")
            return false
        end
    end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]
  layout "areas_layout"
  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @goal = Goal.new
    @goal.recommendation_id = @recommendation.id
  end

  # GET /recommendations/new
  def new
    @area_id = params[:area_id]
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    area = Area.find(recommendation_params[:area_id])
    if (current_user == area.user || current_user.role == 0) then
      @recommendation = Recommendation.new(recommendation_params)
      respond_to do |format|
        if @recommendation.save
          format.html { redirect_to @recommendation.area }
          format.json { render :show, status: :created, location: @recommendation.area }
        else
          format.html { render :new }
          format.json { render json: @recommendation.errors, status: :unprocessable_entity }
          @area_id = area.id
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
    # Create notifications
    if (current_user.role === 0)then
      Notification.create(recipient: @recommendation.area.user, actor:current_user, action: " agregó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation)
    else
      Notification.create(recipient: User.find_by(role: 0), actor:current_user, action: " agregó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation)
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    if (current_user == @recommendation.area.user || current_user.role == 0) then
      respond_to do |format|
        if @recommendation.update(recommendation_params)
          format.html { redirect_to @recommendation.area }
          format.json { render :show, status: :ok, location: @recommendation.area }
        else
          format.html { render :edit }
          format.json { render json: @recommendation.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
    # Create notifications
    if (current_user.role === 0)then
      Notification.create(recipient: @recommendation.area.user, actor:current_user, action: " editó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation)
    else
      Notification.create(recipient: User.find_by(role: 0), actor:current_user, action: " editó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation)
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    if (current_user == @recommendation.area.user || current_user.role == 0) then
      # Create notifications
      if (current_user.role === 0)then
        Notification.create(recipient: @recommendation.area.user, actor:current_user, action: " eliminó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation.area)
      else
        Notification.create(recipient: User.find_by(role: 0), actor:current_user, action: " eliminó una recomendación al área de " + @recommendation.area.name.to_s, notifiable: @recommendation.area)
      end
      unlink_notifs_recommendation @recommendation, @recommendation.area

      area = Area.find(@recommendation.area_id)
      @recommendation.destroy
      respond_to do |format|
        format.html { redirect_to area }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:name, :area_id, :number, :time_limit, :time_beg)
    end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<%= form_with(model: recommendation, local: true) do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
        <% recommendation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/recommendations/create.js.erb
alert("No se aceptan campos vacíos");

app/views/recommendations/edit.html.erb
<div class="w3-container">
     
        <div class="container-fluid">
            <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1>Área: <%= @recommendation.area.name%> </h1>
                <h2>Recomendación <%=@recommendation.number%>: <%= @recommendation.name%></h2>
                <br>
                <p>
                  <strong>Responsable: </strong>
                  <%= @recommendation.area.user.firstname%>
                  <%= @recommendation.area.user.lastname%>
                </p>
            </div>
        </div>
</div>

<div class="container">



 <div class="form-group" style="width: 80%">
   <h4>Editar recomendación:</h4>
       <%= form_with(model: @recommendation, local: true) do |form| %>
       <div>
        <%if @recommendation.errors.any?%>
          <ul>
            <% @recommendation.errors.full_messages.each do |message| %>
              <font color="crimson"><li><%= message %></li></font>
            <%end%>
          </ul>
        <%end%>
      </div>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Número de la recomendación <font color="red"></font>
             <% end %>
               <%= form.text_field :number, class: 'form-control' %>
           </div>
           <br>
           <div >
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Nombre de la recomendación
             <% end %>
               <%= form.text_field :name, class: 'form-control' %>
               <br>
           </div>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Fecha de inicio
             <% end %>
               <%= form.date_field :time_beg %>
               <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Fecha límite
             <% end %>
               <%= form.date_field :time_limit %>
           </div>
           <br>

           <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
             <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver a la recomendación</button>'.html_safe, @recommendation %>
            <div class="input-group">
              <div class="input-group-prepend">
                <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                  <i class="icon-ok icon-white"></i> Guardar cambios
                <% end %>
              </div>
            </div>
          </div>

       <%end%>
       <br>



    </div>
  </div>
</div>

app/views/recommendations/index.html.erb
 

<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= recommendation.name %></td>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<div class="w3-container">

        <div class="container-fluid">
            <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1>Crear nueva recomendación </h1>
            </div>
        </div>
</div>

<div class="container">

 <div class="form-group" style="width: 80%">
       <%= form_with(model: @recommendation, local: true) do |form| %>
          <div>
            <%if @recommendation.errors.any?%>
              <ul>
                <% @recommendation.errors.full_messages.each do |message| %>
                  <font color="crimson"><li><%= message %></li></font>
                <%end%>
              </ul>
            <%end%>
          </div>
           <div>
            <%= form.hidden_field :area_id, :value => @area_id %>
           </div>
           <div>
             <% a = Area.find(@area_id)%>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Número de la recomendación <font color="red">   (Obligatorio)</font>
             <% end %>
              <%if params[:area_id] != nil %>
                <%= form.text_field :number, class: 'form-control' %>
               <%else%>
               <%= form.text_field :number, class: 'form-control' %>
               <%end%>
           </div>
           <br>
           <div >
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Nombre de la recomendación <font color="red">   (Obligatorio)</font>
             <% end %>
               <%= form.text_field :name, required: true, class: 'form-control' %>
           </div>
           <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Fecha de inicio
             <% end %>
               <%= form.date_field :time_beg, required: true %>
           
               <%= label_tag(type: 'tag') do %>
              <i class="icon-ok icon-white"></i>Fecha límite
             <% end %>
               <%= form.date_field :time_limit, required: true %>
           </div>
           <br>
           <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
             <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver al área</button>'.html_safe, Area.find(@area_id) %>
            <div class="input-group">
              <div class="input-group-prepend">
                   <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                     <i class="icon-ok icon-white"></i> Guardar recomendación
                   <% end %>
              </div>
            </div>
          </div>
       <%end%>
       <br>
    </div>
  </div>
 </div>

app/views/recommendations/show.html.erb
<!-- Page content -->
 <div class="w3-container">
    

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid"">
       <div class="container">
         <h1>Recomendación: <%=@recommendation.number%>. <%= @recommendation.name%></h1>
         <h2>Área: <%=@recommendation.area.number%>. <%= @recommendation.area.name%> </h2>
         <br>
         <p>
           <strong>Responsable: </strong>
           <%= @recommendation.area.user.firstname%>
           <%= @recommendation.area.user.lastname%>
         </p>
         <p>
           <strong>Plazo: </strong>
           <%=@recommendation.time_beg.strftime("%d/%m/%Y")%> - <%=@recommendation.time_limit.strftime("%d/%m/%Y")%>
         </p>
     </div>
   </div>
   </div>


    <div class="container">
      <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
        <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver al área</button>'.html_safe, @recommendation.area %>
       <div class="input-group">
         <div class="input-group-prepend">
           <% if (current_user == @recommendation.area.user || current_user.role == 0) then %>
            <%= link_to '<button type="button" class="btn btn-outline-primary">Editar Recomendación</button>'.html_safe, edit_recommendation_path(@recommendation) %>
           <%end%>
         </div>
       </div>
     </div>
    </div>
   <br>

   <div class="container">
      <div class="card">
          <div class="card-header">
              <a class="card-link" data-toggle="collapse" href="#collapseOne">
              <h5 style= "display: inline;">Metas</h5>
              </a>
              <% if (current_user.role == 0 || current_user == @recommendation.area.user) then %>
                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#mynewgoal">
                    <span class="fa fa-plus">
                </button>
              <% end %>
          </div>
          <div id="collapseOne" class="collapse show" >
            <div class="card-body" id= "container_goals" >
                      <% @recommendation.goals.each do |g| %>
                        
                            <%= render g %>
                            
                      <% end %>
            </div>
          </div>
      </div>
  </div>
  <br>

   <div class="container-fluid">
     <table class="table table-hover" style="width: 80%;" align="center">
       <thead>
         <tr>
           <th scope="col"><strong>Fecha:</strong></th>
           <th scope="col"><strong>Acción:</strong></th>
           <th scope="col">
             <strong>Evidencias:</strong>
           </th>
           <th scope="col"></th>
           <th scope="col"></th>
           <th scope="col">
             <% if (current_user.role == 0 || current_user ==  @recommendation.area.user) then %>
             <%= link_to '<span class="fa fa-plus"></span>'.html_safe, new_evidence_path(:recommendation_id => @recommendation.id) %>
             <% end %>
           </th>
         </tr>
       </thead>
       <tbody>
         <% @recommendation.evidences.each do |evidence| %>
          <tr>
            <td> <%= evidence.day.strftime("%d/%m/%Y")%> </td>
            <td> <%= evidence.action %> </td>
            <td> <%= evidence.title %> </td>
            <td><%= link_to '<span class="fa fa-eye"></span>'.html_safe, evidence%></td>
            <% if (current_user == @recommendation.area.user || current_user.role == 0) then %>
            <td><%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_evidence_path(evidence)%></td>
            <td><%= link_to '<span class="fa fa-times"></span>'.html_safe, evidence, method: :delete, data: { confirm: '¿Está seguro que desea eliminar la evidencia de ' + evidence.title + '?'  }%></td>
            <% else %>
            <td></td>
            <td></td>
            <% end %>
          </tr>
         <% end %>
       </tbody>
     </table>
   </div>


  </div>



<!-- Modal -->


<div class="modal fade" id="mynewgoal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Crear Meta</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%=render partial: 'goals/form' %>

      </div>

    </div>
  </div>
</div>