config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users#, :skip => [:registrations]

  devise_scope :user do
    resources :users
    get 'login', to: 'devise/sessions#new'
    get 'edit', to: 'devise/registrations#edit', as: :edit_myaccount
    delete 'logout', to: 'devise/sessions#destroy'
    get 'users/new', to: 'users#new', as: :sign_up
    post 'users/new', to: 'users#create'
    get 'users', to: 'users#index', as: :index
    patch "users/:id", to: "users#update"
    post 'users/:id/edit', to: 'users#update'
    get 'notifications', to: 'notifications#show', as: :notifications_show
  end



  authenticated :user do
    resources :areas
    post 'areas/:id.pdf', to: 'areas#report', as: :report
    get 'areas/:id.pdf', to: 'areas#report'
    resources :recommendations, except: :index do
      resources :goals
    end
    resources :goals
    resources :alerts
    patch '/hide/:id', to: 'alerts#hide', as: 'hide'
    patch '/unhide/:id', to: 'alerts#unhide', as: 'unhide'


    resources :evidences, except: :index
    resources :evidencefiles, only: [:create, :destroy]
    # Routes for authenticated users
    root to: 'areas#index', as: :authenticated_root
    #get "/areas", to: 'areas#index'
  end

  unauthenticated :user do
    get "/areas", to: redirect('login')
  end
  root to: redirect('login')

  resources :notifications do
    collection do
      get 'mark_as_read'
      get 'remove_all'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :areas

  validates_presence_of :firstname, :lastname

  has_many :notifications, foreign_key: :recipient_id
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < ApplicationController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
   def new
    @user = User.new
   end

  # POST /resource
   def create
    @user = User.create(email: params[:user][:email], firstname: params[:user][:firstname], lastname: params[:user][:lastname], role: params[:user][:role])
        render json: @article
   end

  # GET /resource/edit
   def edit
    redirtect_to :edit_myaccount
     super
   end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout "areas_layout"
  def index
    @users  = User.all
  end

  def show
  end

  def edit
  end

  def update
    if (current_user.role == 0) then
      respond_to do |format|

        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'El usuario ha sido actualizado exitosamente.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
  end


  def new
      @user=User.new
  end

  def create
    if (current_user.role == 0) then
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          RegistrationMailer.registration_email(@user, @user.password).deliver_later
          #redirect_to root_path
          format.html { redirect_to @user, notice: 'El usuario ha sido creada exitosamente.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
  end

  def destroy
    @user.areas.each do |area|
      area.update(user_id: current_user.id)
    end
    if (current_user.role == 0) then
      Notification.where(notifiable: @user).each do |notification|
        notification.destroy
      end
      Notification.where(actor: @user).each do |notification|
        notification.destroy
      end
      @user.destroy

      respond_to do |format|
        format.html { redirect_to :index, notice: 'El usuario se ha eliminado exitosamente.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :role, :area_ids => [])
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/edit.html.erb
    <!-- Page content -->
    <div class="w3-container">

        <div class="container-fluid">
            <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1>Editar usuario </h1>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="form-group" style="width: 80%">
            <%= form_for(@user, url: edit_user_path(@user), html:{method: :post}) do |form| %>
                <%if @user.errors.any?%>
                    <%if @user.errors.full_messages.length > 1%>
                        <h2>Ocurrieron <%=@user.errors.full_messages.length%> errores: </h2>
                    <%else%>
                        <h2>Ocurrió un error: </h2>
                    <%end%>
                    <ul>
                        <% @user.errors.full_messages.each do |message|%>
                            <%if message == "Firstname can't be blank"%>
                                <li>Nombre en blanco</li>
                            <%elsif message == "Lastname can't be blank"%>
                                <li>Apellido en blanco</li>
                            <%elsif message == "Email can't be blank"%>
                                <li>Correo electrónico en blanco</li>
                            <%elsif message == "Email has already been taken"%>
                                <li>El correo electrónico ya está registrado y pertenece a otro usuario</li>
                            <%elsif message == "Password can't be blank"%>
                                <li>Contraseña en blanco</li>
                            <%elsif message == "Password is too short (minimum is 6 characters)"%>
                                <li>La nueva contraseña es muy corta (Mínimo <%=@minimum_password_length%> caracteres)</li>
                            <%elsif message == "Password confirmation doesn't match Password"%>
                                <li>La contraseña nueva y la de confirmación no coinciden</li>
                            <%elsif message == "Email is invalid"%>
                                <li>El correo electrónico es inválido</li>
                            <%else%>
                                <li><%= message %></li>
                            <%end%>
                        <%end%>
                    </ul>
                <%end%>

                <div >
                    <%= label_tag(type: 'tag') do %>
                    <i class="icon-ok icon-white"></i> Nombre
                    <% end %>
                    <%= form.text_field :firstname,required: true, class: 'form-control' %>
                </div>

                <div>
                    <%= label_tag(type: 'tag') do %>
                    <i class="icon-ok icon-white"></i> Apellido
                    <% end %>
                    <%= form.text_field :lastname, required: true,class: 'form-control' %>
                </div>

                <div >
                    <%= label_tag(type: 'tag') do %>
                    <i class="icon-ok icon-white"></i> Correo electrónico
                    <% end %>
                    <%= form.text_field :email, required: true,class: 'form-control' %>
                </div>

                <div>
                    <%= label_tag(type: 'tag') do %>
                    <i class="icon-ok icon-white"></i> Rol
                    <% end %>
                    <div>
                        <%= form.select :role, options_for_select({"Responsable" => 1, "Coordinador" => 0}), class:'form-control'%>
                    </div>
                </div>
                <br>

                <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
                  <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver a usuarios</button>'.html_safe, users_path %>
                 <div class="input-group">
                   <div class="input-group-prepend">
                     <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                         <i class="icon-ok icon-white"></i> Guardar cambios
                     <% end %>
                   </div>
                 </div>
               </div>
                <div>
              </div>
            <%end%>
            <br>

        </div>
    </div>
    
    

app/views/users/index.html.erb
<!-- Page content -->
  <div class="w3-container">

    <div class="container-fluid">
        <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1>Usuarios del sistema </h1>
        </div>

  </div>
  </div>

   <div class="container-fluid">
     <table class="table table-hover" style="width: 70%;" align="center">
       <thead>
         <tr>
           <th scope="col">
             Nombres
           </th>
           <th scope="col">
             Apellidos
           </th>
           <th scope="col">
             Correo electrónico
           </th>
           <th scope="col">
             Rol
           </th>
           <th scope="col">
             Áreas asignadas
           </th>
           <%if current_user.role == 0%>
              <td><%= link_to '<span class="fa fa-plus"></span>'.html_safe, new_user_path() %></td>
           <%else%>
              <th scope="col">
              </th>
            <%end%>

           <th scope="col">
           </th>
         </tr>
       </thead>
       <tbody>
         <% @users.each do |user| %>
           <tr>
             <td><%= user.firstname %></td><td><%= user.lastname %></td><td><%= user.email %></td>
             <%if user.role == 0%>
                <td>Coordinador</td>
            <%else%>
                <td>Responsable</td>
            <%end%>

            <%if user.areas.length == 0%>
              <td>Sin áreas asignadas</td>
            <%else%>
                <td>
                <ul style="list-style-type:none;">
                 <% user.areas.each do |area|%>
                 <li><%= link_to area.name, area%></li>
                 <%end%>
                </ul>
              </td>
            <%end%>
           <% if current_user.role == 0 and current_user != user then %>
             <td><%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_user_path(user) %></td>
             <% if current_user != user then %>
                <td><%= link_to '<span class="fa fa-times"></span>'.html_safe, user, method: :delete, data: { confirm: '¿Está seguro que desea eliminar a '+user.firstname+' '+user.lastname+'?'} %></td>
             <%end%>
           <%else%>
             <td></td>
             <td></td>
           <%end%>
           </tr>
         <% end %>
       </tbody>
     </table>
   </div>
   <div class="container-fluid" style="width: 70%;">
     <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver</button>'.html_safe, root_path %>
   </div>
   </div>

app/views/users/new.html.erb
<div class="w3-container">

        <div class="container-fluid">
            <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1>Crear cuenta nueva </h1>
            </div>
        </div>
</div>

<div class="container">

    <div class="form-group" style="width: 80%">

        <%= form_for(@user, url: users_new_path, html:{method: :post}) do |form| %>
            <%if @user.errors.any?%>
                <%if @user.errors.full_messages.length > 1%>
                    <h2>Ocurrieron <%=@user.errors.full_messages.length%> errores: </h2>
                <%else%>
                    <h2>Ocurrió un error: </h2>
                <%end%>
                <ul>
                    <% @user.errors.full_messages.each do |message|%>
                        <%if message == "Firstname can't be blank"%>
                            <li>Nombre en blanco</li>
                        <%elsif message == "Lastname can't be blank"%>
                            <li>Apellido en blanco</li>
                        <%elsif message == "Email can't be blank"%>
                            <li>Correo electrónico en blanco</li>
                        <%elsif message == "Email has already been taken"%>
                            <li>El correo electrónico ya está registrado y pertenece a otro usuario</li>
                        <%elsif message == "Password can't be blank"%>
                            <li>Contraseña en blanco</li>
                        <%elsif message == "Password is too short (minimum is 6 characters)"%>
                            <li>La nueva contraseña es muy corta (Mínimo <%=@minimum_password_length%> caracteres)</li>
                        <%elsif message == "Password confirmation doesn't match Password"%>
                            <li>La contraseña nueva y la de confirmación no coinciden</li>
                         <%elsif message == "Areas is invalid"%>
                            <li>La opción '---Sin áreas---' no puede incluirse en las áreas asignadas al usuario. Intente de nuevo</li>
                         <%elsif message == "Email is invalid"%>
                            <li>El correo electrónico es inválido</li>
                        <%else%>
                            <li><%= message %></li>

                        <%end%>
                    <%end%>
                </ul>
            <%end%>

            <div >
                <%= label_tag(type: 'tag') do %>
                <i class="icon-ok icon-white"></i> Nombre <font color="red">   (Obligatorio)</font>
                <% end %>
                <%= form.text_field :firstname, required: true, class: 'form-control' %>
            </div>

            <div>
                <%= label_tag(type: 'tag') do %>
                <i class="icon-ok icon-white"></i> Apellido <font color="red">   (Obligatorio)</font>
                <% end %>
                <%= form.text_field :lastname, required: true, class: 'form-control' %>
            </div>

            <div >
                <%= label_tag(type: 'tag') do %>
                <i class="icon-ok icon-white"></i> Correo electrónico <font color="red">   (Obligatorio)</font>
                <% end %>
                <%= form.text_field :email, required: true, class: 'form-control' %>
            </div>

            <div>
                 <%= form.hidden_field :password, :value => Devise.friendly_token.first(8) %>
            </div>

            <div>
                <%= label_tag(type: 'tag') do %>
                <i class="icon-ok icon-white"></i> Rol
                <% end %>
                <div>
                    <%= form.select :role, options_for_select({"Responsable" => 1, "Coordinador" => 0}), class:'form-control'%>
                </div>
            </div>
            <br>

            <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
              <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver</button>'.html_safe, root_path %>
             <div class="input-group">
               <div class="input-group-prepend">
                 <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                     <i class="icon-ok icon-white"></i> Agregar usuario
                 <% end %>
               </div>
             </div>
           </div>


        <%end%>
        <br>

    </div>
</div>

app/views/users/show.html.erb
 <!-- Page content -->
 <div class="w3-container">

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid"">
       <div class="container">
         <p>
           <strong>Nombres:</strong>
           <%= @user.firstname%>
           <strong>Apellidos:</strong>
           <%= @user.lastname%>
           <strong>Rol:</strong>
           <% if @user.role == 0%>
              Coordinador
            <%else%>
              Responsable
            <%end%>
         </p>
          <p>
           <strong>Correo electrónico:</strong>
           <%= @user.email%>
         </p>
     </div>
   </div>
  </div>


   <div class="container">


     <%= link_to '<button type="button" class="btn btn-outline-secondary">Editar</button>'.html_safe, edit_user_path(@user) %> |
     <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver</button>'.html_safe, index_path %>
   </div>

  </div>