config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users#, :skip => [:registrations]

  devise_scope :user do
    resources :users
    get 'login', to: 'devise/sessions#new'
    get 'edit', to: 'devise/registrations#edit', as: :edit_myaccount
    delete 'logout', to: 'devise/sessions#destroy'
    get 'users/new', to: 'users#new', as: :sign_up
    post 'users/new', to: 'users#create'
    get 'users', to: 'users#index', as: :index
    patch "users/:id", to: "users#update"
    post 'users/:id/edit', to: 'users#update'
    get 'notifications', to: 'notifications#show', as: :notifications_show
  end



  authenticated :user do
    resources :areas
    post 'areas/:id.pdf', to: 'areas#report', as: :report
    get 'areas/:id.pdf', to: 'areas#report'
    resources :recommendations, except: :index do
      resources :goals
    end
    resources :goals
    resources :alerts
    patch '/hide/:id', to: 'alerts#hide', as: 'hide'
    patch '/unhide/:id', to: 'alerts#unhide', as: 'unhide'


    resources :evidences, except: :index
    resources :evidencefiles, only: [:create, :destroy]
    # Routes for authenticated users
    root to: 'areas#index', as: :authenticated_root
    #get "/areas", to: 'areas#index'
  end

  unauthenticated :user do
    get "/areas", to: redirect('login')
  end
  root to: redirect('login')

  resources :notifications do
    collection do
      get 'mark_as_read'
      get 'remove_all'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
    validates :content, :expiration, presence: true
    serialize :usersNO,Hash
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]
  layout "areas_layout"

  # GET /alerts
  # GET /alerts.json

  def hide
    @alert = Alert.find(params[:id])
    @alert.usersNO[current_user.id]=0
    @alert.save
    
    respond_to do |format|
      format.js
    end
  end

  def unhide
    @alert = Alert.find(params[:id])
    @alert.usersNO[current_user.id]=1
    @alert.save
    
    respond_to do |format|
      format.js
    end
  end
  
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
        format.js
        send_alertmail
        
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:content, :expiration)
    end
    
    def send_alertmail
      begin  
        emails = User.where(:role => 1).pluck(:email)
        AlertMailer.send_newalert(emails, @alert)
      rescue Net::OpenTimeout => e
        puts "no se envió mail"
      rescue ApplicationMailer => a
        puts "no se envió mail" 
      end
    end
    
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_alert.html.erb
    <tr id = "alert_<%= alert.id %>">
        <td colspan="2"><%=alert.content%>
        <br>
        <b>Fecha límite: <%if alert.expiration !=nil%><%=alert.expiration.strftime("%d/%m/%Y")%><%end%></b>
        
        </td>
        <th>
            <%if current_user.role == 0%>
                <%= link_to '<span class="fa fa-times"></span>'.html_safe, alert, method: :delete, remote: true, data: { confirm: '¿Está seguro?' } %>            
            <%end%>
            <% if alert.id != nil %>
            <%= link_to '<span class="fa fa-eye-slash"></span>'.html_safe, hide_path(alert), method: :patch, remote: true %>
            <% end %>
        </th>
    </tr>

app/views/alerts/_form.html.erb
<%= form_with(model: @alert, remote: true) do |form| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% @alert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :content %> Mensaje: <font color="red">   (Campo obligatorio)</font> 
    <%= form.text_area :content, class:"form-control alert_content" %>
  </div>

  <div class="field">
    <br>
    <% form.label :expiration %> Válida hasta: <font color="red">   (Campo obligatorio)</font>
    <%= form.date_field :expiration, class: "form control alert_expiration"%>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Crear", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/alerts/create.js.erb
if ($(".alert_content").val() != ''  && $(".alert_expiration").val() != '' ){
    $("#myModal").modal('hide');
    $(".alert_content").val('');
    $(".alert_expiration").val('');
    $("#alerts_table").prepend('<%=j render @alert%>');
    $("#alert_<%= @alert.id %>").hide().fadeIn(1000);

}else{
    alert("No se aceptan campos vacíos");
}

app/views/alerts/destroy.js.erb
$("#alert_<%= @alert.id %>").fadeOut(500, function(){
	$(this).remove();
});
$("#alertindex_<%= @alert.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/alerts/edit.html.erb
<h1>Editing Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/hide.js.erb
$("#alert_<%= @alert.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/alerts/index.html.erb
<div class="w3-container">

<p id="notice"><%= notice %></p>

<h1 align="center">Alertas</h1> <br>

<table class="table table-hover" style="width: 80%;" align="center">
  <thead>
    <tr>
      <th>Contenido</th>
      <th>Fecha límite</th>
      <th>Vigente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% alerts = Alert.all.order(expiration: :desc) %>
    <% i = -1 %>
    <% alerts.each do |a|%>
    <% i = i + 1 %>
      <% if (Date.parse(a.expiration.to_s) < Date.today) %>
        <% break %>
      <% end %>
  <% end %>

  <tbody>
    <% @alerts.order(expiration: :desc).each do |alert| %>
      <tr id = "alertindex_<%= alert.id %>">
        <td><%= alert.content %></td>
        <td><%= alert.expiration %></td>
        <td>
        <% if (Date.parse(alert.expiration.to_s) < Date.today) %>
          No
        <% else %>
          Sí
        <% end %>
        </td>
        <td><%if current_user.role == 0%>
                <%= link_to '<span class="fa fa-times"></span>'.html_safe, alert, method: :delete, remote: true, data: { confirm: '¿Está seguro?' } %>
            
            <%end%>
            <% if alert.id != nil && alert.usersNO[current_user.id] == 0%>
              <%= link_to '<span class="fa fa-eye"></span>'.html_safe, unhide_path(alert), method: :patch, remote: true %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/alerts/new.html.erb
<%= render 'form', alert: @alert %>

app/views/alerts/send_alertmail.html.erb
 <tr id = "alert_<%= alert.id %>">
        <td colspan="2"><%=alert.content%>
        <br>
        <b>Fecha límite: <%=alert.expiration%></b>
        
        </td>
        <th>
            <strong>No se pudo enviar correo</strong>
        </th>
    </tr>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @alert.content %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @alert.expiration %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/unhide.js.erb
$("#alerts_table").prepend('<%=j render @alert%>');
$("#alert_<%= @alert.id %>").hide().fadeIn(1000);