config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users#, :skip => [:registrations]

  devise_scope :user do
    resources :users
    get 'login', to: 'devise/sessions#new'
    get 'edit', to: 'devise/registrations#edit', as: :edit_myaccount
    delete 'logout', to: 'devise/sessions#destroy'
    get 'users/new', to: 'users#new', as: :sign_up
    post 'users/new', to: 'users#create'
    get 'users', to: 'users#index', as: :index
    patch "users/:id", to: "users#update"
    post 'users/:id/edit', to: 'users#update'
    get 'notifications', to: 'notifications#show', as: :notifications_show
  end



  authenticated :user do
    resources :areas
    post 'areas/:id.pdf', to: 'areas#report', as: :report
    get 'areas/:id.pdf', to: 'areas#report'
    resources :recommendations, except: :index do
      resources :goals
    end
    resources :goals
    resources :alerts
    patch '/hide/:id', to: 'alerts#hide', as: 'hide'
    patch '/unhide/:id', to: 'alerts#unhide', as: 'unhide'


    resources :evidences, except: :index
    resources :evidencefiles, only: [:create, :destroy]
    # Routes for authenticated users
    root to: 'areas#index', as: :authenticated_root
    #get "/areas", to: 'areas#index'
  end

  unauthenticated :user do
    get "/areas", to: redirect('login')
  end
  root to: redirect('login')

  resources :notifications do
    collection do
      get 'mark_as_read'
      get 'remove_all'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
    validates :name, :user, :number, presence: true
    belongs_to :user
    has_many :recommendations, :dependent => :destroy
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  layout "areas_layout"

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    if (current_user.role == 0) then
      @area = Area.new(area_params)

      respond_to do |format|
        if @area.save
          format.html { redirect_to @area }
          format.json { render :show, status: :created, location: @area }
        else
          format.html { render :new }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
    areas = Area.all
    areas.order(number: :asc)
    # Create notifications
    Notification.create(recipient: @area.user, actor:current_user, action: " creó el área " + @area.name.to_s, notifiable: @area)
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    if (current_user.role == 0) then
      respond_to do |format|
        if @area.update(area_params)
          format.html { redirect_to @area }
          format.json { render :show, status: :ok, location: @area }
          format.pdf {report}
        else
          format.html { render :edit }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end

    # Create notifications
    if (current_user.role === 0)then
      Notification.create(recipient: @area.user, actor:current_user, action: " editó el área de " + @area.name.to_s, notifiable: @area)
    else
      Notification.create(recipient: User.find_by(role: 0), actor:current_user, action: " editó el área de " + @area.name.to_s, notifiable: @area)
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    # Create notifications
    Notification.create(recipient: @area.user, actor:current_user, action: " eliminó el área de " + @area.name.to_s, notifiable: @area.user)

    if (current_user.role == 0) then
      unlink_notifs_area @area, @area.user
      @area.destroy
      respond_to do |format|
        format.html { redirect_to areas_url }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: "No tienes permisos para realizar esta acción"
      return
    end
  end

  def report

    #Se elimina todo
    FileUtils.rm_rf(Dir[Rails.root.join('pdfs', '*')])

    #Se encuentra el area que se desea reportar
    @reported_area = Area.find(params[:id])

    #Se acomoda el período en caso de ser necesario
    if @reported_area.report_date_1 > @reported_area.report_date_2 then
      @reported_area.report_date_1, @reported_area.report_date_2 = @reported_area.report_date_2, @reported_area.report_date_1
    end

    #VARIABLES AUXILIARES
    @recomendaciones_validas =[]#Recomendaciones con evidencias dentro del periodo dado
    @recomendacion #Recomendación actual
    @evidencia #Evidencia actual
    @hay_evidencias #Bandera para indicar si la recomendación tiene evidencias que se puedan mostrar

    #Se toma LA PRIMER RECOMENDACIÓN para pegarla junto con la portada PARA NO DESPERDICIAR ESPACIO

    if @reported_area.recommendations.length > 0
      @recomendacion = @reported_area.recommendations[0]
      #Se ajusta el período de la primer recomendación en caso de ser necesario
      if @recomendacion.time_beg > @recomendacion.time_limit then
        @recomendacion.time_beg, @recomendacion.time_limit = @recomendacion.time_limit, @recomendacion.time_beg
      end

      #Se buscarán evidencias en el período dado por el usuario para saber si generaremos portadas para evidencias en la PRIMER RECOMENDACIÓN
      @hay_evidencias = false
      @recomendacion.evidences.each do |recom|
        if recom.day.between?(@reported_area.report_date_1, @reported_area.report_date_2)
          @hay_evidencias = true
          break
        end
      end
    else
      #SI NO HAY RECOMENDACIONES, ENTONCES SE HACE EL REPORTE VACÍO
      pdf = render_to_string pdf:'Report', template:'areas/report_cover.pdf.erb', :page_height => '11in', :page_width => '8.5in'
      save_path=Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')
      File.open(save_path, 'wb') do |file|
        file << pdf
      end
    end

    if @hay_evidencias then

      #Se recorren las evidencias para guardarlas en un arreglo y después ordenarlas respecto a las fechas
      evidencias_ordenadas = []
      @recomendacion.evidences.each do |ev|
        if ev.day.between?(@reported_area.report_date_1, @reported_area.report_date_2)
          evidencias_ordenadas.append(ev)
        end
      end

      evidencias_ordenadas.sort_by!{ |a| a.day}

      #*************************SE CONSTRUYE LA PRIMER EVIDENCIA******************************+
      #SE METEN LAS FOTITOS
      if evidencias_ordenadas[0].day.between?(@reported_area.report_date_1, @reported_area.report_date_2)
        @evidencia = evidencias_ordenadas[0]
      end

      #SE HACE LA PORTADA DEL REPORTE
      pdf = render_to_string pdf:'Report', template:'areas/report_cover.pdf.erb', :page_height => '11in', :page_width => '8.5in'
      save_path=Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')
      File.open(save_path, 'wb') do |file|
        file << pdf
      end

      #Ahora, se buscan las evidencias en pdf
      @evidencia.evidencefiles.each do |f|
        if f.document.attachment then
          if f.document.filename.to_s.include? "pdf" then

            IO.copy_stream(open(ActiveStorage::Blob.service.send(:path_for, f.document.key)), Rails.root.join('pdfs',
            "evidence#{@recomendacion.to_s.gsub(' ', '')}_#{@evidencia.to_s.gsub(' ', '')}.pdf"))

            pdf = CombinePDF.new
            pdf << CombinePDF.load(Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf'), allow_optional_content: true)
            pdf << CombinePDF.load(Rails.root.join('pdfs',"evidence#{@recomendacion.to_s.gsub(' ', '')}_#{@evidencia.to_s.gsub(' ', '')}.pdf"), allow_optional_content: true)
            pdf.save Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')

          end
        end
      end
      #******************************************************************************************
      #--------------CONTINÚAS METIENDO LAS EVIDENCIAS DE LA PRIMER RECOMENDACIÓN------------
      evidencias_ordenadas.each do |ev|
        if ev != evidencias_ordenadas[0]
          @evidencia = ev
          #SE DECIDE SI SE VA A MOSTRAR LA EVIDENCIA ACTUAL PARA CONSTRUIR LAS PORTADAS NECESARIAS
          if ev.day.between?(@reported_area.report_date_1, @reported_area.report_date_2)

            #Se hace la portada de la evidencia con todo e imágenes
            pdf = render_to_string pdf:'Report', template:'areas/evidence.pdf.erb', :page_height => '11in', :page_width => '8.5in'
            save_path=Rails.root.join('pdfs', 'portada'+@reported_area.to_s.gsub(' ', '')+@reported_area.recommendations.index(@recomendacion).to_s+'.pdf')
            File.open(save_path, 'wb') do |file|
              file << pdf
            end

            #Se agrega esta portada de evidencia con todo e imágenes al reporte que existe hasta el momento
            pdf = CombinePDF.new
            pdf << CombinePDF.load(Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf'), allow_optional_content: true)
            pdf << CombinePDF.load(Rails.root.join('pdfs','portada'+@reported_area.to_s.gsub(' ', '')+@reported_area.recommendations.index(@recomendacion).to_s+'.pdf'), allow_optional_content: true)
            pdf.save Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')

            #Se elimina la portada de la evidencia con todo e imágenes porque ya no es util
            File.delete(Rails.root.join('pdfs','portada'+@reported_area.to_s.gsub(' ', '')+@reported_area.recommendations.index(@recomendacion).to_s+'.pdf')) if File.exist?(Rails.root.join('pdfs','portada'+@reported_area.to_s.gsub(' ', '')+@reported_area.recommendations.index(@recomendacion).to_s+'.pdf'))

            #Ahora, se buscan las evidencias en pdf
            ev.evidencefiles.each do |f|
              if f.document.attachment then
                if f.document.filename.to_s.include? "pdf" then

                  IO.copy_stream(open(ActiveStorage::Blob.service.send(:path_for, f.document.key)), Rails.root.join('pdfs',
                  "evidence#{@recomendacion.to_s.gsub(' ', '')}_#{ev.to_s.gsub(' ', '')}.pdf"))

                  pdf = CombinePDF.new
                  pdf << CombinePDF.load(Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf'), allow_optional_content: true)
                  pdf << CombinePDF.load(Rails.root.join('pdfs',"evidence#{@recomendacion.to_s.gsub(' ', '')}_#{ev.to_s.gsub(' ', '')}.pdf"), allow_optional_content: true)
                  pdf.save Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')

                end
              end
            end
          end
        end
      end
    else
      #SI NO HAY EVIDENCIAS, ENTONCES SE HACE EL REPORTE VACÍO
      pdf = render_to_string pdf:'Report', template:'areas/report_cover.pdf.erb', :page_height => '11in', :page_width => '8.5in'
      save_path=Rails.root.join('pdfs', 'reporte'+@reported_area.to_s.gsub(' ', '')+'.pdf')
      File.open(save_path, 'wb') do |file|
        file << pdf
      end
    end
 

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
        <% area.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<!-- Page content -->
 <div class="w3-container">
    

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid">
       <div class="container">
           <h1>Área: <%= @area.name%></h1>
           <br>
           <p>
             <strong>Responsable:</strong>
             <%= @area.user.firstname%>
             <%= @area.user.lastname%>
           </p>
        </div>
      </div>
   </div>

  <div class="container">


   <div class="form-group" style="width: 80%">
       <%= form_with(model: @area) do |form| %>
       <h1>Editar Área </h1>
           <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Nombre del área
             <% end %>
               <%= form.text_field :name, class: 'form-control' %>
           </div>
           <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Descripción del área
             <% end %>
               <%= form.text_area(:description, size:"10x10", class: 'form-control') %>
           </div>
           <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Responsable del área
             <% end %>
             <%= form.select :user_id, User.all.collect { |u| [u.firstname+" "+u.lastname, u.id] }, class:'form-control'%>
           </div>
           <br>
           <br>

           <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
              <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver al área</button>'.html_safe, @area %>
            <div class="input-group">
              <div class="input-group-prepend">
                   <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                     <i class="icon-ok icon-white"></i> Guardar cambios
                   <% end %>
              
              </div>
            </div>
          </div>

       <%end%>
       <br>



    </div>
  </div>
     </div>

app/views/areas/evidence.pdf.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">

</head>
<body>

    <h1 style="sans-serif; font-family:arial; font-size:27px" align="center">Evidencia</h1>

    <div style="width:100%;" >
        <div>
            <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-family:arial; font-size:20px; text-align:justify;"><b>Título: </b> <%=@evidencia.title%></pre>
        </div>
        <br>

        <%numero_evidencia_separado = @evidencia.action.split(".")%>
        <%num_de_rec = numero_evidencia_separado[0]+"."+numero_evidencia_separado[1]+"."+numero_evidencia_separado[2]%>
        <%num_de_meta = numero_evidencia_separado[3].to_i%>
        <%num_de_accion = numero_evidencia_separado[4].to_i%>
        <%puts "SE BUSCARÁ LA RECOMENDACIÓN NÚMERO: "+num_de_rec.to_s%>
        <%puts "Numero de recomendacion: "+num_de_rec.to_s%>
        <%puts "Numero de meta: "+num_de_meta.to_s%>
        <%puts "Numero de acción: "+num_de_accion.to_s%>

        <%recomendacion = nil%>
        <%@reported_area.recommendations.each do |recom|%>
            <%if recom.number.include? num_de_rec%>
                <%recomendacion = recom%>
                 <%puts "SE ENCONTRÓ LA RECOMENDACIÓN:"+num_de_rec%>
                <%break%>
            <%end%>
        <%end%>

        <%@accion = recomendacion.goals[num_de_meta-1].actions.split("\n")[num_de_accion-1]%>

        <br>
        <div>
            <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-family:arial; font-size:20px; text-align:justify;"><b>Acción:</b> <br> <%=@evidencia.action%>. <%=@accion%></pre>
        </div>
        <br>
        
        <div>
            <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-family:arial; font-size:20px; text-align:justify;">
                <%description_content = @evidencia.description.split("\n")%>
                <%if description_content.length > 0%>
                    <b>Descripción:</b>
                    <br/>
                    <%description_content.each do |paragraph|%>
                        <%=paragraph%>
                        <br/>
                    <%end%>
                <%else%>
                   <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-family:arial; font-size:20px; text-align:center;"><b>(SIN DESCRIPCIÓN)</b> </pre>
                <%end%>
            </pre>
        </div>

        <br><br>

        <div>
            <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-family:arial; font-size:20px; text-align:center;"><b>Fecha:</b> <%=@evidencia.day.strftime("%d/%m/%y")%></pre>

        </div>
        <br><br><br>

        <%if @evidencia.evidencefiles.length == 0%>
            <div>
                <pre style="width:100%; overflow:hidden; word-break:normal; white-space:normal; font-size:20px; font-family:arial; text-align:center;"><u><b>(NO EXISTEN ARCHIVOS CARGADOS EN ESTA EVIDENCIA)</b></u></pre>
            </div>
        <%end%>

        <%@evidencia.evidencefiles.each do |file|%>
            <%if file.document.attachment%>
                <%if file.document.filename.to_s.exclude? "pdf" then%>

                    <img style="display:block; margin-left:auto; margin-right:auto; width:100%" src="<%=ActiveStorage::Blob.service.send(:path_for, file.document.key)%>", width="auto", height="auto">
                    <br>

                <%end%>
            <%end%>
        <%end%>

    </div>





</body>
</html>

app/views/areas/index.html.erb
<!-- Page content -->
 <div class="w3-container">

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid"">
       <div class="container">
         <h1>Bienvenido al sistema de GAPCO</h1>
         <p>Gestión de Acreditación del Programa CONAIC</p>
         <br>
     </div>
   </div>
   </div>


   <div class="container-fluid">
   <p scope="col"><strong>Categorías CONAIC para revisión y seguimiento</strong></p>
     <table class="table table-hover" style="width: 80%;" align="center">
       <thead>
         <tr>
           <!--<th scope="col">
             Categorías CONAIC para revisión y seguimiento
           </th> -->
           <th scope="col"></th>
           <th scope="col"></th>
           <th scope="col" style="opacity: 0.5;">Responsable de área</th>
           <th scope="col"></th>
           <th scope="col"></th>
           <% if current_user.role == 0 %>
           <th scope="col">
             <%= link_to '<span class="fa fa-plus"></span>'.html_safe, new_area_path  %>
           </th>
           <%else%>
           <th scope="col"></th>
           <%end%>
         </tr>
       </thead>
       <tbody>
          <% @areas.order(number: :asc) %>
          <% @areas.each do |area| %>
           <tr>
              <td><%= link_to area.number, area %>. </td>
              <td><%= link_to area.name, area %></td>
              <td><%= area.user.firstname%> <%= area.user.lastname%></td>
             <td><%= link_to '<span class="fa fa-eye"></span>'.html_safe, area %></td>
             <% if (current_user.role == 0) then %>
              <td><%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_area_path(area) %></td>
             <%else%>
              <td></td>
             <%end%>
             <% if current_user.role == 0 %>
              <td><%= link_to '<span class="fa fa-times"></span>'.html_safe, area, method: :delete, data: { confirm: '¿Está seguro que desea eliminar el área de ' + area.name + '?'  } %></td>
             <%else%>
              <td></td>
             <%end%>
           </tr>
         <% end %>
       </tbody>
     </table>
   </div>

   </div>

app/views/areas/new.html.erb
 <!-- Page content -->
 <div class="w3-container">
    

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid"">
       <div class="container">
         <h1>Nueva Área</h1>
         <p>Gestión de Acreditación del Programa CONAIC</p>
       </div>
    </div>
   </div>
  
  <div class="container">
   
   

   <div class="form-group" style="width: 80%">
       <%= form_with(model: @area, local: true) do |form| %>
           <div>
             <% a = Area.all.length%>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Número del área <font color="red">   (Obligatorio)</font>
             <% end %>
               <%= form.text_field :number, class: 'form-control' %>
           </div>
           <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Nombre del área <font color="red">   (Obligatorio)</font>
             <% end %>
               <%= form.text_field :name, class: 'form-control' %>
          </div>
          <br>
           <div>
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Descripción del área
             <% end %>
               <%= form.text_area(:description, class: 'form-control', size:"10x10") %>
           </div>
           <br>
           <div >
             <%= label_tag(type: 'tag') do %>
               <i class="icon-ok icon-white"></i> Responsable del área <font color="red">   (Obligatorio)</font>
             <% end %>
             <%= form.select :user_id, User.all.collect { |u| [u.firstname.to_s+" "+u.lastname.to_s, u.id] }, class:'form-control'%>
           </div>
           <br>


           <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
             <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver</button>'.html_safe, areas_path %>
            <div class="input-group">
              <div class="input-group-prepend">
                   <%= button_tag(type: 'submit', class: "btn btn-outline-primary") do %>
                     <i class="icon-ok icon-white"></i> Guardar área
                   <% end %>
              </div>
            </div>
          </div>
       <%end%>
       <br>
    </div>
  </div>
</div>

app/views/areas/show.html.erb
 <!-- Page content -->
 <div class="w3-container">
    

   <div class="container-fluid">
     <div class="jumbotron jumbotron-fluid">
       <div class="container">
         <h1>Área <%=@area.number%>: <%= @area.name%></h1>
         <br>
         <p>
           <strong>Responsable:</strong>
           <%= @area.user.firstname%>
           <%= @area.user.lastname%>
         </p>

         <%description_content = @area.description.split("\n")%>
         <%if description_content.length > 0%>
            <p><strong>Descripción:</strong> </p>

                <%description_content.each do |paragraph|%>
                  <%=paragraph%>
                  <br/>
              <%end%>
          <%else%>
            <p><strong>(Sin descripción)</strong> </p>
            <br/>
          <%end%>
          <br/>

         <% if (current_user == @area.user || current_user.role == 0) then %>
            <button data-toggle="modal" align="right" type="button" class="btn btn-outline-primary" data-target="#myupdategoal_<%= @area.id%>">Generar reporte</button>
            
         <%end%>
     </div>
   </div>
   </div>


   <div class="container">

     <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
       <%= link_to '<button type="button" class="btn btn-outline-secondary">Volver a áreas</button>'.html_safe, root_path %>
      <div class="input-group">
        <div class="input-group-prepend">
          <% if (current_user.role == 0) then %>
          <%= link_to '<button align="right" type="button" class="btn btn-outline-primary">Editar Área</button>'.html_safe, edit_area_path(@area) %>
          <%end%>
        </div>
      </div>
    </div>

   </div>
   <br>
   <div class="container-fluid">
     <table class="table table-hover" style="width: 80%;" align="center">
       <thead>
         <tr>
           <th scope="col">
             <strong>Recomendaciones:</strong>
           </th>
           <th scope="col"></th>
           <th scope="col"></th>
           <th scope="col"></th>
           <% if (current_user == @area.user || current_user.role == 0) then %>
              <th scope="col">
                <%= link_to '<span class="fa fa-plus"></span>'.html_safe, new_recommendation_path(:area_id => @area.id) %>
                <!-- <%= link_to '<span class="fa fa-plus"></span>'.html_safe, new_recommendation_path(:recommendation => { :area_id => @area.id })  %> -->
              </th>
            <%else%>
              <th></th>
            <%end%>
         </tr>
       </thead>
       <tbody>
         <% @area.recommendations.each do |r| %>
           <tr>
              <td><%= link_to r.number, r %> </td>
              <td><%= link_to r.name, r %></td>
              <td><%= link_to '<span class="fa fa-eye"></span>'.html_safe, r %></td>
              <% if (current_user == @area.user || current_user.role == 0) then %>
              <td><%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_recommendation_path(r) %></td>
              <td><%= link_to '<span class="fa fa-times"></span>'.html_safe, r, method: :delete, data: { confirm: '¿Está seguro que desea eliminar la recomendación de ' + r.name + '?'  } %></td>
              <%else%>
              <td></td>
              <td></td>
              <%end%>
           </tr>
         <% end %>
       </tbody>
     </table>
   </div>
    <%= form_for(@area, :url=>{:action=>:report}) do |form| %>
    <div class="modal fade" id="myupdategoal_<%= @area.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Periodo del reporte</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <table>
              <tr>
                   <div class="field" align="center">
                      <% form.label :report_date_1%>Fecha inicial:  
                      <%= form.date_field (:report_date_1), required: true, :value => Time.new,class: 'form-control'%>
                    </div>
                   <br>
                    <div class="field" align="center">
                      
                      <% form.label :report_date_2%>Fecha final:
                      <span style="padding-left:9px">
                        <%= form.date_field (:report_date_2), required: true, :value => Time.new, class: 'form-control'%>
                      </span>
                    </div>
              </tr>
            </table>
           
            
          </div>
          <div class="modal-footer">

            <button type="button" id="myupdatebutton_<%= @area.id%>" class="btn btn-default" data-dismiss="modal">Salir</button>
            <%= form.submit "Crear", class: "btn btn-primary", data: {disable_with: "Generando reporte..."}%>
          </div>
        </div>
      </div>
    </div>
    <%end%>


   </div>